apiVersion: apps/v1
kind: Deployment
metadata:
  name: auction-svc
spec:
  selector:
    matchLabels:
      app: auction-svc
  template:
    metadata:
      labels:
        app: auction-svc
    spec:
      containers:
      - name: auction-svc
        image: juliuss97/auction-svc
        imagePullPolicy: Never
        env:
          - name: ConnectionStrings__DefaultConnection
            valueFrom:
              secretKeyRef:
                name: auction-secret
                key: connString
          - name: RabbitMQ_Username
            valueFrom:
              secretKeyRef:
                name: rabbit-secret
                key: username
          - name: RabbitMQ_Password
            valueFrom:
              secretKeyRef:
                name: rabbit-secret
                key: password
        envFrom:
          - configMapRef:
              name: auction-svc-config
        ports:
        - containerPort: 80
          name: web
        - containerPort: 7777
          name: grpc
---
apiVersion: v1
kind: Service
metadata:
  name: auction-clusterip
spec:
  type: ClusterIP
  selector:
    app: auction-svc
  ports:
  - port: 80
    targetPort: 80
    name: web
  - port: 7777
    targetPort: 7777
    name: grpc

